# You can see the configuration in ~/.config/yowsup/$PHONE_NUMBER_WITH_COUNTRY_CODE/config.json

# The name generated by `"😊".encode("utf-8")`` For unicode string do it.
name = "\xf0\x9f\x98\x8a" # => 😊

credentials = {
  "PHONE": "PHONE_NUMBER",
  "CLIENT_STATIC_KEYPAIR": "CLIENT_STATIC_KEYPAIR",
}

